apiVersion: v1
kind: Secret
metadata:
  name: {{ include "milansql.fullname" . }}-secret
  labels:
    {{- include "milansql.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ .Values.config.rootPassword | default (randAlphaNum 32) | b64enc | quote }}
