#!/usr/bin/env python3
"""
tools/amalgamate.py — Phase 117: Single-header amalgamation for milansql_embedded

Produces dist/milansql_embedded_amalgam.h by inlining all transitive
#include'd project headers into a single file.  Standard library headers
(<string>, <vector>, …) are kept as-is.  Duplicate project includes are
collapsed to one copy.

Usage:
    python tools/amalgamate.py
    # → writes dist/milansql_embedded_amalgam.h
"""

import os
import sys
import re
from pathlib import Path

ROOT        = Path(__file__).resolve().parent.parent          # repo root
SRC_DIRS    = [ROOT / "src", ROOT / "include"]
ENTRY_POINT = ROOT / "include" / "milansql_embedded.h"
OUT_DIR     = ROOT / "dist"
OUT_FILE    = OUT_DIR / "milansql_embedded_amalgam.h"

# ── helpers ──────────────────────────────────────────────────────

def is_project_header(path: Path) -> bool:
    """Return True if the file lives under the project root."""
    try:
        path.resolve().relative_to(ROOT)
        return True
    except ValueError:
        return False

def resolve_include(inc_path: str, current_file: Path) -> Path | None:
    """Try to resolve a quoted include relative to the current file, then
    against SRC_DIRS.  Return None if not found (treat as system header)."""
    if inc_path.startswith("/"):
        return None                          # absolute — leave to compiler

    # 1. Relative to including file's directory
    candidate = (current_file.parent / inc_path).resolve()
    if candidate.exists():
        return candidate

    # 2. Search src dirs
    for d in SRC_DIRS:
        candidate = (d / inc_path).resolve()
        if candidate.exists():
            return candidate

    return None


def process_file(path: Path,
                 visited: set,
                 out_lines: list,
                 depth: int = 0) -> None:
    """Recursively inline project headers; emit system headers once."""
    path = path.resolve()
    if path in visited:
        return
    visited.add(path)

    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        print(f"WARNING: cannot read {path}: {e}", file=sys.stderr)
        return

    out_lines.append(f"\n// ────── BEGIN {path.relative_to(ROOT)} ──────\n")

    for line in text.splitlines(keepends=True):
        m = re.match(r'\s*#\s*include\s*[<"]([^>"]+)[">]', line)
        if not m:
            out_lines.append(line)
            continue

        inc_str  = m.group(1)
        resolved = resolve_include(inc_str, path)

        if resolved and is_project_header(resolved):
            # Inline the project header recursively
            process_file(resolved, visited, out_lines, depth + 1)
        else:
            # System / external header — emit once
            if line not in visited:          # type: ignore[operator]
                out_lines.append(line)
                visited.add(line)            # type: ignore[arg-type]

    out_lines.append(f"\n// ────── END   {path.relative_to(ROOT)} ──────\n")


# ── main ─────────────────────────────────────────────────────────

def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    visited: set   = set()
    out_lines: list = []

    banner = (
        "/*\n"
        " * milansql_embedded_amalgam.h — auto-generated single-header amalgamation\n"
        " * MilanSQL v5.8.0 Embedded Mode\n"
        " *\n"
        " * Generated by tools/amalgamate.py\n"
        " * DO NOT EDIT — regenerate with: python tools/amalgamate.py\n"
        " */\n\n"
        "#pragma once\n"
        "#ifndef MILANSQL_AMALGAM_H\n"
        "#define MILANSQL_AMALGAM_H\n\n"
    )
    out_lines.append(banner)

    process_file(ENTRY_POINT, visited, out_lines)

    out_lines.append("\n#endif /* MILANSQL_AMALGAM_H */\n")

    OUT_FILE.write_text("".join(out_lines), encoding="utf-8")
    print(f"Amalgamation written to {OUT_FILE}")
    print(f"Total size: {OUT_FILE.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
